### ISSUE TITLE
React-Redux Group project setup

### ISSUE THREAD

**Issue by jonas-45** [jonas-45/space-travellers-hub#25]
https://github.com/jonas-45/space-travellers-hub/projects/1
We are two team members; @jonas-45 and @rica213

**Comment by DuaneDave** [comment]
Hi @jonas-45 and @rica213 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Kanban board set up is correct
✔️ Issue is opened as specified

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jonas-45** [comment]
Thank you for your time and effort.
